# Generated by Django 5.1.4 on 2025-01-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="sub_title",
            new_name="price",
        ),
    ]
