# Generated by Django 5.1.4 on 2025-01-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_banner_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='position',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
