# Generated by Django 5.1.4 on 2025-01-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_rename_sub_title_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="testimonial/"),
        ),
    ]
