# Generated by Django 5.1.4 on 2025-01-04 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_alter_testimonial_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
    ]
