# Generated by Django 5.1.4 on 2025-01-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_blog_category_blog_date_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
